/// ----------
/// keyboard.h
/// @brief This file declares and defines important strucuters relating to the keyboard.
#ifndef KEYBOARD_H
#define KEYBOARD_H

#include <stdint.h>
#include <stdbool.h>

typedef struct keyboard_key_s{
    uint16_t index;
    char* keyname;
    char value;

    bool is_pressed;
    bool previously_pressed;
}keyboard_key_t;

typedef keyboard_key_t* keyboard_map_t;

typedef void (*keyboard_input_handle_t)(keyboard_key_t keyboard_key, const keyboard_map_t keyboard_map);

typedef enum {
    KEY_NONE            = 0,
    KEY_ESCAPE          = 1,
    KEY_1               = 2,
    KEY_2               = 3,
    KEY_3               = 4,
    KEY_4               = 5,
    KEY_5               = 6,
    KEY_6               = 7,
    KEY_7               = 8,
    KEY_8               = 9,
    KEY_9               = 10,
    KEY_0               = 11,
    KEY_MINUS           = 12,
    KEY_EQUAL           = 13,
    KEY_BACKSPACE       = 14,
    KEY_TAB             = 15,
    KEY_Q               = 16,
    KEY_W               = 17,
    KEY_E               = 18,
    KEY_R               = 19,
    KEY_T               = 20,
    KEY_Y               = 21,
    KEY_U               = 22,
    KEY_I               = 23,
    KEY_O               = 24,
    KEY_P               = 25,
    KEY_LEFT_BRACKET    = 26,
    KEY_RIGHT_BRACKET   = 27,
    KEY_ENTER           = 28,
    KEY_LEFT_CONTROL    = 29,
    KEY_A               = 30,
    KEY_S               = 31,
    KEY_D               = 32,
    KEY_F               = 33,
    KEY_G               = 34,
    KEY_H               = 35,
    KEY_J               = 36,
    KEY_K               = 37,
    KEY_L               = 38,
    KEY_SEMICOLON       = 39,
    KEY_APOSTROPHE      = 40,
    KEY_BACKTICK        = 41,
    KEY_LEFT_SHIFT      = 42,
    KEY_BACKSLASH       = 43,
    KEY_Z               = 44,
    KEY_X               = 45,
    KEY_C               = 46,
    KEY_V               = 47,
    KEY_B               = 48,
    KEY_N               = 49,
    KEY_M               = 50,
    KEY_COMMA           = 51,
    KEY_PERIOD          = 52,
    KEY_SLASH           = 53,
    KEY_RIGHT_SHIFT     = 54,
    KEY_MULTIPLY        = 55,
    KEY_LEFT_ALT        = 56,
    KEY_SPACEBAR        = 57,
    KEY_CAPS_LOCK       = 58,
    KEY_F1              = 59,
    KEY_F2              = 60,
    KEY_F3              = 61,
    KEY_F4              = 62,
    KEY_F5              = 63,
    KEY_F6              = 64,
    KEY_F7              = 65,
    KEY_F8              = 66,
    KEY_F9              = 67,
    KEY_F10             = 68,
    KEY_NUM_LOCK        = 69,
    KEY_SCROLL_LOCK     = 70,
    KEY_HOME            = 71,
    KEY_UP_ARROW        = 72,
    KEY_PAGE_UP         = 73,
    KEY_NUM_MINUS       = 74,
    KEY_LEFT_ARROW      = 75,
    KEY_CENTER_ARROW    = 76,
    KEY_RIGHT_ARROW     = 77,
    KEY_NUM_PLUS        = 78,
    KEY_END             = 79,
    KEY_DOWN_ARROW      = 80,
    KEY_PAGE_DOWN       = 81,
    KEY_INSERT          = 82,
    KEY_DELETE          = 83,
    KEY_NUM_0           = 84,
    KEY_NUM_1           = 85,
    KEY_NUM_2           = 86,
    KEY_NUM_3           = 87,
    KEY_NUM_4           = 88,
    KEY_NUM_5           = 89,
    KEY_NUM_6           = 90,
    KEY_NUM_7           = 91,
    KEY_NUM_8           = 92,
    KEY_NUM_9           = 93,
    KEY_NUM_DIVIDE      = 94,
    KEY_NUM_MULTIPLY    = 95,
    KEY_NUM_SUBTRACT    = 96,
    KEY_NUM_ADD         = 97,
    KEY_NUM_ENTER       = 98,
    KEY_UNUSED_99       = 99,
    KEY_UNUSED_100      = 100,
    KEY_UNUSED_101      = 101,
    KEY_UNUSED_102      = 102,
    KEY_UNUSED_103      = 103,
    KEY_UNUSED_104      = 104,
    KEY_UNUSED_105      = 105,
    KEY_UNUSED_106      = 106,
    KEY_UNUSED_107      = 107,
    KEY_UNUSED_108      = 108,
    KEY_UNUSED_109      = 109,
    KEY_UNUSED_110      = 110,
    KEY_UNUSED_111      = 111,
    KEY_UNUSED_112      = 112,
    KEY_UNUSED_113      = 113,
    KEY_UNUSED_114      = 114,
    KEY_UNUSED_115      = 115,
    KEY_UNUSED_116      = 116,
    KEY_UNUSED_117      = 117,
    KEY_UNUSED_118      = 118,
    KEY_UNUSED_119      = 119,
    KEY_UNUSED_120      = 120,
    KEY_UNUSED_121      = 121,
    KEY_UNUSED_122      = 122,
    KEY_UNUSED_123      = 123,
    KEY_UNUSED_124      = 124,
    KEY_UNUSED_125      = 125,
    KEY_UNUSED_126      = 126,
    KEY_UNUSED_127      = 127
} keyboard_keycode_t;

#endif